set t_Co=256

" This is for WSL, see https://github.com/Microsoft/WSL/issues/1706
set term=screen-256color
set t_ut=

" Pathogen
execute pathogen#infect()
syntax on
filetype plugin indent on

" No sounds when cursor blocked or whatever
set visualbell

" Makes vim behave like most editors:
" - The current buffer can be put to the background without writing to disk;
" - When a background buffer becomes current again, marks and undo-history are remembered.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

set history=1000

syntax enable
set number
set relativenumber
set ruler " shows in status line where you are in the file

" Do not activate hlsearch by default. See below that F3 lets you toggle it.
" set hlsearch

set incsearch
set ignorecase " often you want to ignore case when searching for text
set smartcase  " will turn on case-sensitivity only if the text to search contains uppercase characters, which is what you often want
set autoindent

" Necessary since switch from vim 7.4 to 8.1.
set backspace=indent,eol,start

" Shows selection size information in bottom line while in visual mode
set showcmd

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" Will not cut words in the middle when wrap is on
set linebreak

"This makes sure a minimum number of lines is always visible above the cursor
set scrolloff=10

" Allows using the mouse to resize window splits!
set mouse=n

" Scroll the viewport (without moving the cursor) 3x faster
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" Tell vim where to put its backup files
" WARNING: Make sure directory exists or you can get weird errors (in NERDTree on opening, for instance)
set backupdir=~/.vim/tmp

" Tell vim where to put swap files
" WARNING: Make sure directory exists or you can get weird errors (in NERDTree on opening, for instance)
set dir=~/.vim/tmp

set background=dark

colorscheme PaperColor

" Background color approximation of what is in my Xresources in URxvt.background
" If you don't do this, by default vim will use all default colors of the
" terminal emulator, except for the background+foreground which will match
" with the chosen colorscheme.
hi Terminal ctermbg=234 ctermfg=grey

" <Leader>bg will switch color scheme between light and dark
" (restoring ModeMsg is important in this case, otherwise it's lost)
map <Leader>bg :let &background = ( &background == "dark"? "light" : "dark" )<CR>:hi ModeMsg ctermfg=white ctermbg=darkred<cr>

"<Leader> = \ by default

" source $MYVIMRC reloads the saved $MYVIMRC
:nmap <Leader>S :source $MYVIMRC

" opens $MYVIMRC for editing, or use :tabedit $MYVIMRC
:nmap <Leader>v :e $MYVIMRC

"-----------------------------------
"This unsets the "last search pattern" register by hitting return
"nnoremap <CR> :noh<CR><CR>

"set cursorline
"hi CursorLine term=NONE cterm=NONE ctermbg=none ctermfg=none

hi ModeMsg ctermfg=white ctermbg=darkred

" Change Color when entering Insert Mode
" autocmd InsertEnter * highlight  CursorLine ctermbg=darkred ctermfg=white

" Revert Color to default when leaving Insert Mode
" autocmd InsertLeave * highlight  CursorLine ctermbg=none ctermfg=none

" enable status line always
set laststatus=2

" redraw only when we need to.
set lazyredraw

set wildmenu            " visual autocomplete for command menu

" Indicate that the specified cscope commands must put their results in the quickfix window.
" The minus sign indicates to clear the quickfix window before putting the results.
set cscopequickfix=s-,c-,d-,i-,t-,e-,g-

let NERDTreeShowHidden=1
let NERDTreeMinimalUI=1 " Disables display of the 'Bookmarks' label and 'Press ? for help' text
let g:NERDTreeWinSize=60
let g:NERDTreeWinPos = "right"

" Shift-F3 = previous match
" nnoremap <C-[>O1;2R N

" F3 = next match
" nnoremap <F3> n

" Quick save and exit
nnoremap <Leader><Leader> :xa<CR>

" Toggle NERDTree and switch to it
map <Leader>1 :NERDTreeToggle<CR>

" Toggle wrap in all windows (works in vimdiff) and show new value in current window.
nnoremap <Leader>2 :windo set wrap! wrap?<CR>

" Toggle search results highlighting
nnoremap <Leader>3 :set hlsearch!<CR>

" Toggle showing whitespace characters
nnoremap <Leader>4 :set list!<CR>

" Show the most important whitespace characters
set listchars=tab:>-,trail:·,eol:$

" Go to previous error in quickfix window
nnoremap _ :cp<CR>

" Go to next error in quickfix window
nnoremap + :cn<CR>

" https://stackoverflow.com/questions/657447/vim-clear-last-search-highlighting
" Double escape clears search pattern
nnoremap <silent> <Esc><Esc> :let @/=""<CR>

" Switch between windows easily
nnoremap <F12> <C-w><C-w>
tmap <F12> <C-w><C-w> " Make it work in terminal buffer too, without this line F12 outputs a tilda character

" Switch between buffers easily (does not seem to work everywhere)
nnoremap <Insert> :bp<CR>
nnoremap <Home> :bn<CR>

" Switch between buffers easily
nnoremap <C-S-p> :bprevious<CR>
nnoremap <C-S-n> :bnext<CR>

" Switch between tabs easily
nnoremap <Delete> :tabp<CR>
nnoremap <End> :tabn<CR>

" Easy shortcut to switch terminal to Terminal-Normal mode
tnoremap <Leader>i <C-W>N

" Note the trailing space
inoremap <C-B> <3 

iabbrev coeur cœur
iabbrev oeil œil
iabbrev ps: P.-S.:
iabbrev ps2: P.-S.2:
iabbrev 3c <3 <3 <3... :)
iabbrev 4c <3 <3 <3 <3... :)
iabbrev 5c <3 <3 <3 <3 <3... :)
iabbrev 6c <3 <3 <3 <3 <3 <3... :)
iabbrev 7c <3 <3 <3 <3 <3 <3 <3... :)
iabbrev 8c <3 <3 <3 <3 <3 <3 <3 <3... :)
iabbrev 9c <3 <3 <3 <3 <3 <3 <3 <3 <3... :)
iabbrev 10c <3 <3 <3 <3 <3 <3 <3 <3 <3 <3... :)
iabbrev 11c <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3... :)
iabbrev 12c <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3... :)
iabbrev 13c <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3... :)
iabbrev 14c <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3... :)
iabbrev 15c <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3... :)

"set switchbuf+=usetab,newtab

" This is for CTRL+n autocompletion while in insert mode.
" The above command will change the 'completeopt' option so that Vim's popup menu doesn't select the first completion item, but rather just inserts the longest common text of all matches; and the menu will come up even if there's only one match. (The longest setting is responsible for the former effect and the menuone is responsible for the latter.) 
set completeopt=longest,menuone

" The following will make the cursor move by display lines when long lines are wrapping
" Source: http://vim.wikia.com/wiki/Move_cursor_by_display_lines_when_wrapping
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
nnoremap <Down> gj
nnoremap <Up> gk
vnoremap <Down> gj
vnoremap <Up> gk
inoremap <Down> <C-o>gj
inoremap <Up> <C-o>gk

" Make - and + (in fact =) make browsing code with less RSI
noremap - 4gk
noremap = 4gj

" Quick save file (only if changed) and restore previous mode if any
nmap <Leader>s :update<CR>
vmap <Leader>s <Esc><Leader>sgv
imap <Leader>s <c-o><Leader>s

" Back tick as replacement for Esc. Tab is good too but as soon as you start
" programming, you regret it.
imap ` <Esc>

" Since tilda is now taken in insert mode, provide a way to write a tilda in
" insert mode using C-V C-V
inoremap <C-V><C-V> <C-V>u0060

" Make shift-Tab decrease indent like in most editors
inoremap <S-Tab> <C-d>

" Set up cursor behaviour:
if &term =~ "xterm\\|rxvt"
    " use an cursor of a certain color in insert mode
    let &t_SI = "\<Esc>]12;red\x7"
    " use a another cursor color otherwise
    let &t_EI = "\<Esc>]12;gray\x7"
    silent !echo -ne "\033]12;gray\007"
    " reset cursor when vim exits
    autocmd VimLeave * silent !echo -ne "\033]12;gray\007"
endif

" Makes yanking and pasting use the X clipboard. Prepend it because their is a
" default value already (probably the exclude statement in the default value
" is the cause)
set clipboard^=unnamed

" Disable default clipboard behavior that makes visual mode copy to clipboard
" on each change of visual selection.
set clipboard-=autoselect

" This makes the buffers created for terminal use to be marked as 'unlisted'.
" This prevents :bp and :bn to cycle on these windows and get stuck on the
" shell prompt if the terminal is not in normal mode. Another example of
" unlisted buffer is the NERDTree buffer. Type !ls to see all buffers included
" unlisted ones. Source for this solution: https://github.com/jalvesaq/Nvim-R/issues/340
autocmd TerminalOpen * set nobuflisted

let g:OmniSharp_server_path = '/mnt/f/tools/omnisharp.http-win-x64/OmniSharp.exe'
let g:OmniSharp_translate_cygwin_wsl = 1

